### ISSUE TITLE
Issue if User switches back and forth between Stealth / Trident

### ISSUE THREAD

**Issue by QCManufacturing** [jrod-qc/Price-Slider#5]
You're may already aware of this issue, but when a user flips the Fan dropdown back and forth to either Trident or Stealth, it should re-check the values of both the "Select Fan" and "Select Model" dropdowns. If not, it looks like the slider values will remain the same.
Example: 

- User first selects Trident 1.5 and operates slider
- User then selects Stealth 6.0 and operates slider
- User then selects Trident (the 1.5 model appears since it was the model they last selected for Trident). If the user operates the slider, it continues to display values for Stealth 6.0 even though dropdowns say Trident 1.5

**Comment by jrod-qc** [comment]
The Issue has been fixed. Now the results won't be displayed while selecting another fan.
